name: JoFrhwld's Github Blog
description: Josef Fruehwald's technical blog
url: //jofrhwld.github.io/blog
baseurl: //jofrhwld.github.io/blog
permalink: date
exclude: [rmd_drafts]
timezone: Europe/London
analytics: true
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
gems: [jekyll-paginate]