name: JoFrhwld's Github Blog
description: A Github blog
url: //jofrhwld.github.io/blog/
baseurl: //jofrhwld.github.io/blog/
permalink: date
exclude: [rmd_drafts]
timezone: Europe/London
analytics: true