project:
  type: website
  render:
    - "*.qmd"
    - "!old_posts/"
  preview:
    port: 7776

execute:
  freeze: auto

website:
  title: "Væl Space"
  favicon: /assets/logo.svg
  twitter-card:
    image: /assets/logo.svg
  open-graph: 
    image: /assets/logo.svg    
  bread-crumbs: false
  site-url: "https://jofrhwld.github.io/blog"
  reader-mode: true
  google-analytics: "G-SS6YYGWPPL"
  cookie-consent:
    type: express
    palette: dark
  page-navigation: true
  navbar:
    left:
      - href: https://jofrhwld.github.io/
        text: Homepage
      - href: about.qmd
        text: About
      - icon: rss
        href: index.xml
  sidebar:
    logo: assets/logo.svg  
    style: floating
    contents: posts
    collapse-level: 0
    
      
  # sidebar: 
  #   style: "floating"
  #   search: true
  #   contents: 
  #     - href: https://jofrhwld.github.io/
  #       text: "my homepage"

format:
  html:
    theme:
      light: 
        - flatly
        - styles/custom.scss
        - styles/light.scss
      dark: 
        - darkly
        - styles/custom.scss
        - styles/dark.scss
    toc: true
    fig-width: 6
    fig-height: 5
    title-block-banner: true
    license: "CC-BY-SA 4.0"
    smooth-scroll: true
    code-link: true
    lightbox: true

editor: visual
