project:
  type: website
  output-dir: "docs"
  render:
    - "*.qmd"
    - "!old_posts/"  

execute:
  freeze: auto

website:
  title: "Væl Space"
  site-url: "https://jofrhwld.github.io/blog"
  google-analytics: "G-SS6YYGWPPL"
  cookie-consent:
    type: express
    palette: dark
  page-navigation: true
  navbar:
    left:
      - href: https://jofrhwld.github.io/
        text: Homepage
      - href: about.qmd
        text: About
      - icon: rss
        href: index.xml
  sidebar:
    collapse-level: 0
    style: floating
    contents: posts
      
  # sidebar: 
  #   style: "floating"
  #   search: true
  #   contents: 
  #     - href: https://jofrhwld.github.io/
  #       text: "my homepage"

format:
  html:
    theme: 
      - "darkly"
      - custom.scss
    include-in-header: font_import.html
    monofont: Fira Code
    mainfont: Atkinson Hyperlegible
    toc: true
    fig-width: 6
    fig-height: 5
    title-block-banner: true
    license: "CC-BY-SA 4.0"
    smooth-scroll: true

editor: visual