{
  "hash": "ca09d4fd21bdeab4807eccef1742cf65",
  "result": {
    "markdown": "---\ntitle: \"Rising Wooders: Part 2\"\nsubtitle: \"Part 2: Saying Wooder\"\nauthor: \"Josef Fruehwald\"\ndate: 2023-01-01\ncategories:\n  - \"research\"\n  - \"linguistics\"\nimage: \"index_files/figure-html/fig-spectrogram-1.png\"\ntwitter-card: \n  image: \"index_files/figure-html/fig-spectrogram-1.png\"\n  card-style: summary_large_image\n  creator: \"@jofrhwld\"\nopen-graph:\n  image: \"index_files/figure-html/fig-spectrogram-1.png\"\nknitr: \n  opts_chunk: \n    message: false\nbibliography: references.bib\norder: 01\n---\n\n\nThis is part 2 of my blog posts to accompany my ADS2023 Poster.\n\n[![](/posts/2022/12/2022-12-31_wooder1/assets/ADS2023-wooder.png){fig-alt=\"The full American Dialect Society poster for \\\"Philadelphians' say Wooder, and that's that\\\"?\"}](/posts/2022/12/2022-12-31_wooder1/assets/ADS2023-wooder.png)\n\n## Saying Wooder\n\nAs I said in [the previous post](../../../2022/12/2022-12-31_wooder1/index.qmd), people seem to be very aware *now* that pronouncing \"water\" as \\[wʊɾɚ\\] is a feature of Philadelphia English, but the surge in written recognition from 2000 onwards isn't an accurate indicator of when people *started* pronouncing it that way.\n\nThe order in which I actually approached this is a little different from how it's laid out in the poster, but for the sake of blogginess, I'll describe it in more chronological order. My bias was that this was a very old feature of Philadelphia English, so I started with the oldest records of Philadelphia speech I know of in the Linguistic Linguistic Atlas of the Middle and South Atlantic States (LAMSAS) [@kretzschmar1993].\n\n## Written Records\n\nLAMSAS was a linguistic atlas project carried out between 1933 and 1974. The interviews had a heavy focus on regional and dialect words, and for the earliest interviews, the only records available are fieldworker transcriptions. In 1939, Guy Lowman interviewed 8 people in Philadelphia, and for one target item, transcribed how they pronounced \"glass/tumbler of water.\"\n\n| LAMSAS ID | Gender | Race  | Age | Year of Birth |\n|-----------|--------|-------|----:|--------------:|\n| PA1G      | man    | white |  70 |          1869 |\n| PA1A      | man    | white |  68 |          1871 |\n| PA1C      | woman  | white |  68 |          1871 |\n| PA1E      | man    | white |  68 |          1871 |\n| PA1D      | man    | white |  66 |          1873 |\n| PA1F      | man    | white |  62 |          1877 |\n| PA1H      | woman  | white |  59 |          1880 |\n| PA1B      | man    | white |  43 |          1896 |\n\n: LAMSAS Informant Demographics\n\nI'm not going to have much more to say about these LAMSAS speakers, though, because they were *all* transcribed as saying \\[wɔɾɚ\\], which would be the same vowel as in *wall* or *walk*, not as in *wood*. In fact, I've done some more combing through the LAMSAS records from counties surrounding Philadelphia in both Pennsylvania and New Jersey, and there are *no* records of \\[wʊɾɚ\\].\n\n### Wooderless?\n\nOn the one hand, I was really surprised by this, but I don't know why I should have been. There's really no reason why \\[wʊɾɚ\\] should have been a long-standing feature of the dialect as long as a century ago. Moreover, @Tucker1944 is often cited as the earliest description of the Philadelphia dialect,[^1] and he includes a few word-by-word descriptions that ring true based on my own Philly upbringing like:\n\n[^1]: Although, he offers no information for the *basis* of how he came to describe the dialect. As in, this is more like his collected observations, but he doesn't even really say that either.\n\n-   \"*spigot*, pronounced *spicket* and commonly used for 'faucet.'\"\n\n-   \"*taffy* 'lollipop,' known in some places as a 'sucker.'\"\n\n-   \"*yo* \\[...\\] used especially by children in calling one another\"\n\nOthers must've fallen out of use before my time, and I'm completely unfamiliar with them, such as\n\n-   \"*yakers* (or *yakes* or *yacks*), or *yakers on it!* 'I claim it'; also Goods (on it)I 'I claim a share.'\"\n\n-   \"*this after*, short for 'this afternoon.'\"\n\nThe point, though, is that he does not mention anything about the word \"water\" at all. So sometime around the early 1940s, the pronunciation \\[wʊɾɚ\\] was either non-existent or used too infrequently for either Tucker or Lowman to note it.\n\n## Acoustics\n\nThis is where I would normally turn to acoustic data in the Philadelphia Neighborhood Corpus, but there are a few complications there. First and foremost, I really don't trust any automated system to be able to place a firm boundary between where the /w/ ends and the vowel begins in a word like \"water\", especially because I wouldn't really trust myself to be able to do so. So, while I *do* have access to acoustic data for all tokens of \"water\", I don't have a high degree of trust in them as they are.\n\nThe exciting news is that the longest ago born person in the PNC (1890) overlaps with the latest born person in LAMSAS (1896), meaning we have some degree of data continuity in year of births ranging from 1869 through to 1990. But, the fact that the LAMSAS data only exists in transcription form means I need to do things the old fashioned way and listen to all of these tokens and impressionistically code them.\n\nSo that's what I did, starting with the speaker born in 1890.\n\n### Worder!\n\nI've really lucked out that the speaker born in 1890 (interviewed in 1973) talked about water a *lot*. And, to my surprise, l coded most of his pronunciations as \\[wɔɾɚ\\], just like Guy Lowman's informants from 1939. However, while he never said \\[wʊɾɚ\\], there were a bunch of tokens where I could hear an \\[ɹ\\] before the flap, and could see a falling F3, characteristic of \\[ɹ\\]s as well. Here's a representative spectrogram.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"libraries\"}\nlibrary(tidyverse)\nlibrary(khroma)\nlibrary(scales)\nlibrary(geomtextpath)\nlibrary(ggnewscale)\n\nlibrary(tuneR)\nlibrary(seewave)\n\nlibrary(readtextgrid)\n\nsource(here::here(\"_defaults.R\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"loading data\"}\nwater_wav <- readWave(\"data/water.wav\")\nwater_formant <- read_csv(\"data/water.csv\")\nwater_tg <- read_textgrid(\"data/water.TextGrid\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"spectrogram processing\"}\nwater_wav |> \n  spectro(\n    # window length, in terms of samples\n    wl = 0.005 * water_wav@samp.rate, \n    # window overlap\n    ovlp = 90, \n    plot = F\n    ) -> spect\n\n# \"dynamic range\"\ndyn <- -50\n\ncolnames(spect$amp) <- spect$time\nrownames(spect$amp) <- spect$freq\n\nspect_df <- \n  spect$amp |> \n  as_tibble(rownames = \"freq\") |> \n  pivot_longer(-freq, names_to = \"time\", values_to = \"amp\") |> \n  mutate(freq = as.numeric(freq),\n           time = as.numeric(time)) |> \n  # floor at the dynamic range\n  mutate(amp = case_when(amp <= dyn ~ dyn,\n                         TRUE ~ amp)) \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"textgrid processing\"}\nwater_labels <- \n  water_tg |> \n  filter(tier_num == 1) |> \n  mutate(ipa_label = case_when(text == \"W\" ~ \"wɔ(ɹ)\",\n                               text == \"AO1\" ~ \"wɔ(ɹ)\",\n                               text == \"T\" ~ \"ɾ\",\n                               text == \"ER0\" ~ \"ɚ\")) |> \n  group_by(ipa_label) |> \n  summarise(\n    xmin = min(xmin),\n    xmax = max(xmax)\n    ) |> \n  arrange(xmin) |> \n  rowwise() |> \n  mutate(midpoint = median(c(xmin, xmax)))\n\nwater_boundaries <- \n  water_labels |> \n  select(-midpoint) |> \n  pivot_longer(-ipa_label) |> \n  select(value) |> \n  distinct()\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"formant track processing\"}\nformant_df <- \n  water_formant |> \n  select(time, f1, f2, f3) |> \n  pivot_longer(\n    -time, \n    names_to = \"formant\",\n    values_to = \"hz\"\n    ) |> \n  mutate(\n    formant = toupper(formant),\n    formant_num = str_extract(formant, \"\\\\d\"),\n    formant_num = as.numeric(formant_num)\n    )\n```\n:::\n\n::: {.cell crop='true'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"plotting code\"}\nspect_df |> \n  ggplot(aes(time, freq*1000))+\n    stat_contour(\n      aes(z = amp, fill = after_stat(level)),\n      geom = \"polygon\",\n      bins = 500\n      )+\n    scale_fill_grayC(reverse = T, guide = \"none\")+\n    geom_vline(\n      data = water_boundaries, \n      aes(xintercept = value),\n      linetype = 2, \n      color = \"grey70\"\n      )+\n    geom_text(\n      data = water_labels,\n      aes(\n        x = midpoint, \n        label = ipa_label\n        ),\n      family = \"Fira Sans\",\n      y = 5000,\n      size = 6\n    )+\n    new_scale_fill()+\n    geom_labelline(\n      data = formant_df,\n      aes(\n        x = time,\n        y = hz,\n        fill = formant,\n        color = formant,\n        label = formant,\n        hjust = formant_num/10\n        ),\n      textcolor = \"white\",\n      linewidth = 1.5\n      )+\n    scale_fill_manual(\n      values = c(\"#33BBEE\", \"#EE3377\", \"#009988\"),\n      guide = \"none\"\n    )+\n    scale_color_manual(\n      values = c(\"#33BBEE\", \"#EE3377\", \"#009988\"),\n      guide = \"none\"\n    )+\n    scale_y_continuous(expand = expansion(mult = 0),\n                       labels = label_comma())+\n    coord_cartesian(ylim = c(0, 5500))+\n    labs(\n      x = \"time (s)\", \n      y = \"freq (hz)\",\n      title = '\"water\" spectrogram',\n      subtitle = str_wrap(\n        \"sample token from a speaker born in 1890\n        with a dropping F3 prior to the flap\",\n        width = 40\n        )\n      )+\n    theme(aspect.ratio = 5/8,\n          text = element_text(size = 16),\n          plot.subtitle = element_text(size = 10, color = \"grey80\"),\n          plot.caption = element_text(size = 10, color = \"grey80\"))\n```\n\n::: {.cell-output-display}\n![Spectrogram of a token of 'water' from the PNC, illustrating a dropping F3 prior to the flap.](index_files/figure-html/fig-spectrogram-1.png){#fig-spectrogram fig-alt='Spectrogram of a token of \\'water\\' from the PNC, illustrating a dropping F3 prior to the flap.' width=576}\n:::\n:::\n\n\n### The coding scheme\n\nThis pronunciation with an \\[ɹ\\] hasn't really been discussed by anyone, but it is reminiscent of how *daughter* is sometimes pronounced in Philly, as they recently (kinda[^2]) portrayed in the SNL satirization of *Mare of Easttown*, [*Murder Durder*](https://www.youtube.com/watch?v=qaKZi6p6sxg).\n\n[^2]: What's off about the SNL sketch is they pronounce the first syllable of *daughter* with the [Nurse]{.smallcaps} vowel, \\[ɚ\\], when it should be something ranging between \\[ɔɹ\\] to \\[ʊɹ\\].\n\nI had to take this variant into account in my coding. In fact, I think it's actually key to understanding where *wooder* came from. So my coding scheme had the following values:\n\n-   ʊ - any high, rounded realization without a \\[ɹ\\]\n\n-   ɔɹ - any mid to high-ish rounded realization with a \\[ɹ\\]\n\n-   ɔ - any lowish to mid rounded realization without an \\[ɹ\\]\n\n-   ɑ - any low, unrounded realization\n\nThis unrounded variant mostly shows up when people are talking *about* the pronunciation of *water*, but not exclusively.\n\n### The model\n\nSince this is already getting to be a pretty long post, I'll just skip to the model results! I fit a multilevel multinomial logistic regression model[^3] with these 4 variants as outcomes.\n\n[^3]: More specifically, I fit the model using `brms::brm` like so\n\n    ``` r\n    brm(\n        data = data,\n        family = categorical(\n          link = logit,\n          refcat = \"1_oh\"\n          ),\n        code_param ~ decade + (1|idstring),\n      )\n    ```\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"libraries\"}\nlibrary(brms)\nlibrary(tidybayes)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"load brms model\"}\nmodel <- read_rds(\"data/multinomial_linear.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"get model estimates\"}\nnewdat <- tibble(\n  dob = 1869:1990,\n  decade = (dob - 1950)/10\n  )\n\nests <- \n  newdat |> \n  add_epred_draws(model, re_formula = NA) |> \n  group_by(dob, .category) |> \n  median_hdci(.epred, .width = seq(0.2, 0.8, by = 0.1)) |> \n  mutate(code = case_when(.category == \"0_a\" ~ \"ɑ\",\n                          .category == \"1_oh\" ~ \"ɔ\",\n                          .category == \"2_ohr\" ~ \"ɔr\",\n                          .category == \"3_u\" ~ \"ʊ\"), \n         code = as.factor(code) |> fct_rev()) \n```\n:::\n\n::: {.cell crop='true'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"plot code\"}\nests |> \n ggplot(aes(dob))+\n    geom_ribbon(\n      aes(\n        ymin = .lower, \n        ymax = .upper, \n        group = paste(.width, .category), \n        fill = .category\n        ),\n      alpha = 0.2)+\n    scale_fill_bright(guide = \"none\")+\n    facet_wrap(~code)+\n    scale_y_continuous(\n      expand = expansion(mult = 0), \n      limits = c(0,1), \n      breaks = c(0, 0.5, 1)\n      )+\n    labs(x = \"year of birth\",\n         y = \"vowel probability\",\n         title = \"variant probability\",\n         subtitle = str_wrap(\n           \"the probability of one of four vowel variants in water'\n           being used for different year of birth cohorts, as modeled by a\n           multinomial logistic regression\",\n           width = 60\n           )\n         )+\n    theme(aspect.ratio = 5/8,\n          text = element_text(size = 16),\n          plot.subtitle = element_text(size = 8, color = \"#ebebeb\"),\n         ) \n```\n\n::: {.cell-output-display}\n![Modeled estimates of the probability of one of the 4 vowel variants being used in *water*.](index_files/figure-html/fig-variant-prob-1.png){#fig-variant-prob fig-alt='\"A plot with 4 facets, 1 for each vowel variannt.\n ɔ starts off near 100% then declines from 1869 to 1990.\n ʊ starts off close to 0%, then increases to about 75% between 1869 to 1990.\n ɔr starts off close to 0%, rises to about 25%, then falls again to close to 0%\n a only appears to be just above 0% in the most recent time periods.\"\n' width=576}\n:::\n:::\n\n\n## Wooder on the rise\n\nSo it looks like the shift from \\[wɔɾɚ\\] to \\[wʊɾɚ\\] was shift that occurred in Philadelphia during the 20^th^ century alongside many others. But it also seems like it was not as simple as a categorical pronunciation jump nor a gradual shift from \\[ɔ\\] to \\[ʊ\\] because we also have this rhotic variant \\[wɔɹɾɚ\\] in the mix.\n\nI actually think the \\[wɔɹɾɚ\\] variant is key to figuring out how we got from \\[wɔɾɚ\\] to \\[wʊɾɚ\\], specifically because of another pattern in Philadelphia English, r-dissimilation, which I'll hopefully write up for a post tomorrow!\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}