name: Build Site
on:
  push:
    branches: ["master"]
    
env:
  RENV_PATHS_ROOT: ~/.cache/R/renv
  QUARTO_PYTHON: renv/python/virtualenvs/renv-python-3.12/bin/python
jobs:
  build-docs:
     runs-on: macos-latest
     steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - uses: r-lib/actions/setup-r@v2
      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      - name: Install Reticulate
        run: Rscript -e 'renv::install("reticulate")'
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
      # - name: Set Quarto Python
      #   run: |
      #     echo "QUARTO_PYTHON=renv/python/virtualenvs/renv-python-3.12/bin/python" >> $GITHUB_ENV
      - name: Render and publish to gh pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
