name: Build Site
on:
  push:
    branches: ["master"]
    
env:
  RENV_PATHS_ROOT: ~/.cache/R/renv    
    
jobs:
  build-docs:
     runs-on: macos-latest
     steps:
      - uses: actions/checkout@v2
      # - name: Setup Fortran
      #   uses: fortran-lang/setup-fortran@v1.3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          
      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
          
      - name: Install Reticulate
        run: Rscript -e 'renv::install("reticulate")'
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render and publish to gh pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
